language: lua

env:
  - LUAJIT_VERSION="master" TEST_BIN="luajit test/tools/run.lua" PRELOAD="libpthread.so.0"
  # - LUAJIT_VERSION="v2.1" TEST_BIN="luajit-2.1.0-alpha test/tools/run.lua" PRELOAD="libpthread.so.0"

# Handle git submodules yourself
git:
  submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

compiler:
  - gcc

script: "sudo LUAJIT_VERSION=$LUAJIT_VERSION bash test/tools/install.sh && LD_PRELOAD=\"$PRELOAD\" $TEST_BIN"

branches:
  only:
    - master
    - feature/messaging_system

install:
  - sudo apt-get install luarocks

notifications:
  recipients:
    - iyatomi+luact.test@gmail.com
  email:
    on_success: change
    on_failure: always
