language: lua

env:
  #- LUAJIT_VERSION="v2.1" TEST_BIN="luajit-2.1.0-alpha test/bootstrap/test.lua" PRELOAD="libpthread.so.0"
  - LUAJIT_VERSION="master" TEST_BIN="luajit test/tools/run.lua" PRELOAD="/usr/local/lib/libjemalloc.so.1 libpthread.so.0"
  - LUAJIT_VERSION="v2.1" TEST_BIN="luajit-2.1.0-alpha test/tools/run.lua" PRELOAD="/usr/local/lib/libjemalloc.so.1 libpthread.so.0"

compiler:
  - gcc

script: "sudo LUAJIT_VERSION=$LUAJIT_VERSION bash test/tools/install.sh && LD_PRELOAD=\"$PRELOAD\" $TEST_BIN"

branches:
  only:
    - master
    - feature/messaging_system

install:
  - sudo apt-get install luarocks

notifications:
  recipients:
    - iyatomi+luact.test@gmail.com
  email:
    on_success: change
    on_failure: always

